package fi.omasaasahko.domain

/**
 * Every distinct weather description the FMI SmartSymbol and WMO code tables produce.
 * Each entry is one complete sentence per language, so translations can inflect freely.
 * The first entries mirror [Condition] and serve as its default descriptions.
 */
enum class WeatherText {
    CLEAR, MOSTLY_CLEAR, PARTLY_CLOUDY, MOSTLY_CLOUDY, CLOUDY,
    DRIZZLE, FREEZING_DRIZZLE, FREEZING_RAIN, RAIN, SLEET, SNOW,
    HAIL, THUNDER, THUNDER_HAIL, FOG, UNKNOWN,

    // FMI SmartSymbol
    ISOLATED_SHOWERS, SCATTERED_SHOWERS, SHOWERS,
    PARTLY_CLOUDY_LIGHT_RAIN, PARTLY_CLOUDY_MODERATE_RAIN, PARTLY_CLOUDY_HEAVY_RAIN,
    MOSTLY_CLOUDY_LIGHT_RAIN, MOSTLY_CLOUDY_MODERATE_RAIN, MOSTLY_CLOUDY_HEAVY_RAIN,
    LIGHT_RAIN, MODERATE_RAIN, HEAVY_RAIN,
    ISOLATED_LIGHT_SLEET_SHOWERS, ISOLATED_MODERATE_SLEET_SHOWERS, ISOLATED_HEAVY_SLEET_SHOWERS,
    SCATTERED_LIGHT_SLEET_SHOWERS, SCATTERED_MODERATE_SLEET_SHOWERS, SCATTERED_HEAVY_SLEET_SHOWERS,
    LIGHT_SLEET, MODERATE_SLEET, HEAVY_SLEET,
    ISOLATED_LIGHT_SNOW_SHOWERS, ISOLATED_MODERATE_SNOW_SHOWERS, ISOLATED_HEAVY_SNOW_SHOWERS,
    SCATTERED_LIGHT_SNOW_SHOWERS, SCATTERED_MODERATE_SNOW_SHOWERS, SCATTERED_HEAVY_SNOW_SHOWERS,
    LIGHT_SNOW, MODERATE_SNOW, HEAVY_SNOW,
    ISOLATED_HAIL_SHOWERS, SCATTERED_HAIL_SHOWERS, HAIL_SHOWERS,
    ISOLATED_THUNDER_SHOWERS, SCATTERED_THUNDER_SHOWERS, THUNDER_SHOWERS,

    // WMO (Open-Meteo)
    FREEZING_FOG, LIGHT_DRIZZLE, MODERATE_DRIZZLE, DENSE_DRIZZLE,
    LIGHT_FREEZING_DRIZZLE, DENSE_FREEZING_DRIZZLE, LIGHT_FREEZING_RAIN, HEAVY_FREEZING_RAIN, SNOW_GRAINS,
    LIGHT_RAIN_SHOWERS, MODERATE_RAIN_SHOWERS, HEAVY_RAIN_SHOWERS, LIGHT_SNOW_SHOWERS, HEAVY_SNOW_SHOWERS,
    THUNDER_LIGHT_HAIL, THUNDER_HEAVY_HAIL,
}
